/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.AssociatedCasesInnerAssociatedCases = factory(root.CourtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AssociatedCasesInnerAssociatedCases model module.
   * @module model/AssociatedCasesInnerAssociatedCases
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>AssociatedCasesInnerAssociatedCases</code>.
   * associated case data
   * @alias module:model/AssociatedCasesInnerAssociatedCases
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>AssociatedCasesInnerAssociatedCases</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssociatedCasesInnerAssociatedCases} obj Optional instance to populate.
   * @return {module:model/AssociatedCasesInnerAssociatedCases} The populated <code>AssociatedCasesInnerAssociatedCases</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('case_uri')) {
        obj['case_uri'] = ApiClient.convertToType(data['case_uri'], 'String');
      }
      if (data.hasOwnProperty('case_id')) {
        obj['case_id'] = ApiClient.convertToType(data['case_id'], 'Number');
      }
      if (data.hasOwnProperty('case_name')) {
        obj['case_name'] = ApiClient.convertToType(data['case_name'], 'String');
      }
      if (data.hasOwnProperty('case_code')) {
        obj['case_code'] = ApiClient.convertToType(data['case_code'], 'String');
      }
      if (data.hasOwnProperty('case_type')) {
        obj['case_type'] = ApiClient.convertToType(data['case_type'], 'String');
      }
    }
    return obj;
  }

  /**
   * Case Uri
   * @member {String} case_uri
   */
  exports.prototype['case_uri'] = undefined;
  /**
   * Case External ID
   * @member {Number} case_id
   */
  exports.prototype['case_id'] = undefined;
  /**
   * Case Title
   * @member {String} case_name
   */
  exports.prototype['case_name'] = undefined;
  /**
   * Case Number
   * @member {String} case_code
   */
  exports.prototype['case_code'] = undefined;
  /**
   * Case Type
   * @member {String} case_type
   */
  exports.prototype['case_type'] = undefined;



  return exports;
}));


