/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssociatedCasesInnerAssociatedCases', 'model/AssociatedCasesInnerCase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AssociatedCasesInnerAssociatedCases'), require('./AssociatedCasesInnerCase'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.AssociatedCasesInnerText = factory(root.CourtApi.ApiClient, root.CourtApi.AssociatedCasesInnerAssociatedCases, root.CourtApi.AssociatedCasesInnerCase);
  }
}(this, function(ApiClient, AssociatedCasesInnerAssociatedCases, AssociatedCasesInnerCase) {
  'use strict';




  /**
   * The AssociatedCasesInnerText model module.
   * @module model/AssociatedCasesInnerText
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>AssociatedCasesInnerText</code>.
   * @alias module:model/AssociatedCasesInnerText
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AssociatedCasesInnerText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AssociatedCasesInnerText} obj Optional instance to populate.
   * @return {module:model/AssociatedCasesInnerText} The populated <code>AssociatedCasesInnerText</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('case')) {
        obj['case'] = AssociatedCasesInnerCase.constructFromObject(data['case']);
      }
      if (data.hasOwnProperty('associated_cases')) {
        obj['associated_cases'] = AssociatedCasesInnerAssociatedCases.constructFromObject(data['associated_cases']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AssociatedCasesInnerCase} case
   */
  exports.prototype['case'] = undefined;
  /**
   * @member {module:model/AssociatedCasesInnerAssociatedCases} associated_cases
   */
  exports.prototype['associated_cases'] = undefined;



  return exports;
}));


