/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CaseAliasInnerText'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CaseAliasInnerText'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.CaseAliasInner = factory(root.CourtApi.ApiClient, root.CourtApi.CaseAliasInnerText);
  }
}(this, function(ApiClient, CaseAliasInnerText) {
  'use strict';




  /**
   * The CaseAliasInner model module.
   * @module model/CaseAliasInner
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>CaseAliasInner</code>.
   * @alias module:model/CaseAliasInner
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CaseAliasInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseAliasInner} obj Optional instance to populate.
   * @return {module:model/CaseAliasInner} The populated <code>CaseAliasInner</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], [CaseAliasInnerText]);
      }
      if (data.hasOwnProperty('meta')) {
        obj['meta'] = ApiClient.convertToType(data['meta'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CaseAliasInnerText>} text
   */
  exports.prototype['text'] = undefined;
  /**
   * Various metadata like time modified, case_uuid, and bunch of unused legacy fieleds
   * @member {Object} meta
   */
  exports.prototype['meta'] = undefined;



  return exports;
}));


