/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.CaseMeta = factory(root.CourtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CaseMeta model module.
   * @module model/CaseMeta
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>CaseMeta</code>.
   * @alias module:model/CaseMeta
   * @class
   */
  var exports = function() {
    var _this = this;












































  };

  /**
   * Constructs a <code>CaseMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseMeta} obj Optional instance to populate.
   * @return {module:model/CaseMeta} The populated <code>CaseMeta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('assets')) {
        obj['assets'] = ApiClient.convertToType(data['assets'], 'String');
      }
      if (data.hasOwnProperty('assigned_to')) {
        obj['assigned_to'] = ApiClient.convertToType(data['assigned_to'], 'String');
      }
      if (data.hasOwnProperty('case_chapter_id')) {
        obj['case_chapter_id'] = ApiClient.convertToType(data['case_chapter_id'], 'Number');
      }
      if (data.hasOwnProperty('case_court_id')) {
        obj['case_court_id'] = ApiClient.convertToType(data['case_court_id'], 'Number');
      }
      if (data.hasOwnProperty('case_id')) {
        obj['case_id'] = ApiClient.convertToType(data['case_id'], 'Number');
      }
      if (data.hasOwnProperty('case_id_external')) {
        obj['case_id_external'] = ApiClient.convertToType(data['case_id_external'], 'Number');
      }
      if (data.hasOwnProperty('case_no')) {
        obj['case_no'] = ApiClient.convertToType(data['case_no'], 'String');
      }
      if (data.hasOwnProperty('case_petition_id')) {
        obj['case_petition_id'] = ApiClient.convertToType(data['case_petition_id'], 'Number');
      }
      if (data.hasOwnProperty('case_title')) {
        obj['case_title'] = ApiClient.convertToType(data['case_title'], 'String');
      }
      if (data.hasOwnProperty('case_type_id')) {
        obj['case_type_id'] = ApiClient.convertToType(data['case_type_id'], 'Number');
      }
      if (data.hasOwnProperty('case_uuid')) {
        obj['case_uuid'] = ApiClient.convertToType(data['case_uuid'], 'String');
      }
      if (data.hasOwnProperty('cause')) {
        obj['cause'] = ApiClient.convertToType(data['cause'], 'String');
      }
      if (data.hasOwnProperty('ch11_type')) {
        obj['ch11_type'] = ApiClient.convertToType(data['ch11_type'], 'String');
      }
      if (data.hasOwnProperty('ch11_type_code')) {
        obj['ch11_type_code'] = ApiClient.convertToType(data['ch11_type_code'], 'Number');
      }
      if (data.hasOwnProperty('chapter')) {
        obj['chapter'] = ApiClient.convertToType(data['chapter'], 'Number');
      }
      if (data.hasOwnProperty('citation')) {
        obj['citation'] = ApiClient.convertToType(data['citation'], 'String');
      }
      if (data.hasOwnProperty('court')) {
        obj['court'] = ApiClient.convertToType(data['court'], 'String');
      }
      if (data.hasOwnProperty('court_name')) {
        obj['court_name'] = ApiClient.convertToType(data['court_name'], 'String');
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = ApiClient.convertToType(data['created'], 'String');
      }
      if (data.hasOwnProperty('date_closed')) {
        obj['date_closed'] = ApiClient.convertToType(data['date_closed'], 'String');
      }
      if (data.hasOwnProperty('date_discharged')) {
        obj['date_discharged'] = ApiClient.convertToType(data['date_discharged'], 'String');
      }
      if (data.hasOwnProperty('date_filed')) {
        obj['date_filed'] = ApiClient.convertToType(data['date_filed'], 'String');
      }
      if (data.hasOwnProperty('date_of_last_filing')) {
        obj['date_of_last_filing'] = ApiClient.convertToType(data['date_of_last_filing'], 'String');
      }
      if (data.hasOwnProperty('date_plan_confirmed')) {
        obj['date_plan_confirmed'] = ApiClient.convertToType(data['date_plan_confirmed'], 'String');
      }
      if (data.hasOwnProperty('date_terminated')) {
        obj['date_terminated'] = ApiClient.convertToType(data['date_terminated'], 'String');
      }
      if (data.hasOwnProperty('disabled')) {
        obj['disabled'] = ApiClient.convertToType(data['disabled'], 'Boolean');
      }
      if (data.hasOwnProperty('disposition')) {
        obj['disposition'] = ApiClient.convertToType(data['disposition'], 'String');
      }
      if (data.hasOwnProperty('has_asset')) {
        obj['has_asset'] = ApiClient.convertToType(data['has_asset'], 'Boolean');
      }
      if (data.hasOwnProperty('industry')) {
        obj['industry'] = ApiClient.convertToType(data['industry'], 'String');
      }
      if (data.hasOwnProperty('is_business_bankruptcy')) {
        obj['is_business_bankruptcy'] = ApiClient.convertToType(data['is_business_bankruptcy'], 'Boolean');
      }
      if (data.hasOwnProperty('judge_name')) {
        obj['judge_name'] = ApiClient.convertToType(data['judge_name'], 'String');
      }
      if (data.hasOwnProperty('jurisdiction')) {
        obj['jurisdiction'] = ApiClient.convertToType(data['jurisdiction'], 'String');
      }
      if (data.hasOwnProperty('jury_demand')) {
        obj['jury_demand'] = ApiClient.convertToType(data['jury_demand'], 'String');
      }
      if (data.hasOwnProperty('liabilities')) {
        obj['liabilities'] = ApiClient.convertToType(data['liabilities'], 'String');
      }
      if (data.hasOwnProperty('modified')) {
        obj['modified'] = ApiClient.convertToType(data['modified'], 'String');
      }
      if (data.hasOwnProperty('naics_code')) {
        obj['naics_code'] = ApiClient.convertToType(data['naics_code'], 'Number');
      }
      if (data.hasOwnProperty('nature_of_debt')) {
        obj['nature_of_debt'] = ApiClient.convertToType(data['nature_of_debt'], 'String');
      }
      if (data.hasOwnProperty('nature_of_suit_code')) {
        obj['nature_of_suit_code'] = ApiClient.convertToType(data['nature_of_suit_code'], 'Number');
      }
      if (data.hasOwnProperty('referred_to')) {
        obj['referred_to'] = ApiClient.convertToType(data['referred_to'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('uri_id')) {
        obj['uri_id'] = ApiClient.convertToType(data['uri_id'], 'Number');
      }
      if (data.hasOwnProperty('website')) {
        obj['website'] = ApiClient.convertToType(data['website'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} assets
   */
  exports.prototype['assets'] = undefined;
  /**
   * @member {String} assigned_to
   */
  exports.prototype['assigned_to'] = undefined;
  /**
   * @member {Number} case_chapter_id
   */
  exports.prototype['case_chapter_id'] = undefined;
  /**
   * @member {Number} case_court_id
   */
  exports.prototype['case_court_id'] = undefined;
  /**
   * @member {Number} case_id
   */
  exports.prototype['case_id'] = undefined;
  /**
   * @member {Number} case_id_external
   */
  exports.prototype['case_id_external'] = undefined;
  /**
   * @member {String} case_no
   */
  exports.prototype['case_no'] = undefined;
  /**
   * @member {Number} case_petition_id
   */
  exports.prototype['case_petition_id'] = undefined;
  /**
   * @member {String} case_title
   */
  exports.prototype['case_title'] = undefined;
  /**
   * @member {Number} case_type_id
   */
  exports.prototype['case_type_id'] = undefined;
  /**
   * @member {String} case_uuid
   */
  exports.prototype['case_uuid'] = undefined;
  /**
   * @member {String} cause
   */
  exports.prototype['cause'] = undefined;
  /**
   * @member {String} ch11_type
   */
  exports.prototype['ch11_type'] = undefined;
  /**
   * @member {Number} ch11_type_code
   */
  exports.prototype['ch11_type_code'] = undefined;
  /**
   * @member {Number} chapter
   */
  exports.prototype['chapter'] = undefined;
  /**
   * @member {String} citation
   */
  exports.prototype['citation'] = undefined;
  /**
   * @member {String} court
   */
  exports.prototype['court'] = undefined;
  /**
   * @member {String} court_name
   */
  exports.prototype['court_name'] = undefined;
  /**
   * @member {String} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {String} date_closed
   */
  exports.prototype['date_closed'] = undefined;
  /**
   * @member {String} date_discharged
   */
  exports.prototype['date_discharged'] = undefined;
  /**
   * @member {String} date_filed
   */
  exports.prototype['date_filed'] = undefined;
  /**
   * @member {String} date_of_last_filing
   */
  exports.prototype['date_of_last_filing'] = undefined;
  /**
   * @member {String} date_plan_confirmed
   */
  exports.prototype['date_plan_confirmed'] = undefined;
  /**
   * @member {String} date_terminated
   */
  exports.prototype['date_terminated'] = undefined;
  /**
   * @member {Boolean} disabled
   */
  exports.prototype['disabled'] = undefined;
  /**
   * @member {String} disposition
   */
  exports.prototype['disposition'] = undefined;
  /**
   * @member {Boolean} has_asset
   */
  exports.prototype['has_asset'] = undefined;
  /**
   * @member {String} industry
   */
  exports.prototype['industry'] = undefined;
  /**
   * @member {Boolean} is_business_bankruptcy
   */
  exports.prototype['is_business_bankruptcy'] = undefined;
  /**
   * @member {String} judge_name
   */
  exports.prototype['judge_name'] = undefined;
  /**
   * @member {String} jurisdiction
   */
  exports.prototype['jurisdiction'] = undefined;
  /**
   * @member {String} jury_demand
   */
  exports.prototype['jury_demand'] = undefined;
  /**
   * @member {String} liabilities
   */
  exports.prototype['liabilities'] = undefined;
  /**
   * @member {String} modified
   */
  exports.prototype['modified'] = undefined;
  /**
   * @member {Number} naics_code
   */
  exports.prototype['naics_code'] = undefined;
  /**
   * @member {String} nature_of_debt
   */
  exports.prototype['nature_of_debt'] = undefined;
  /**
   * @member {Number} nature_of_suit_code
   */
  exports.prototype['nature_of_suit_code'] = undefined;
  /**
   * @member {String} referred_to
   */
  exports.prototype['referred_to'] = undefined;
  /**
   * @member {String} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Number} uri_id
   */
  exports.prototype['uri_id'] = undefined;
  /**
   * @member {String} website
   */
  exports.prototype['website'] = undefined;



  return exports;
}));


