/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CaseAliasInnerParty', 'model/CaseAliasInnerPartyAlias'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CaseAliasInnerParty'), require('./CaseAliasInnerPartyAlias'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.CaseAliasInnerText = factory(root.CourtApi.ApiClient, root.CourtApi.CaseAliasInnerParty, root.CourtApi.CaseAliasInnerPartyAlias);
  }
}(this, function(ApiClient, CaseAliasInnerParty, CaseAliasInnerPartyAlias) {
  'use strict';




  /**
   * The CaseAliasInnerText model module.
   * @module model/CaseAliasInnerText
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>CaseAliasInnerText</code>.
   * @alias module:model/CaseAliasInnerText
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>CaseAliasInnerText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseAliasInnerText} obj Optional instance to populate.
   * @return {module:model/CaseAliasInnerText} The populated <code>CaseAliasInnerText</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('party')) {
        obj['party'] = ApiClient.convertToType(data['party'], [CaseAliasInnerParty]);
      }
      if (data.hasOwnProperty('party_alias')) {
        obj['party_alias'] = ApiClient.convertToType(data['party_alias'], [CaseAliasInnerPartyAlias]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CaseAliasInnerParty>} party
   */
  exports.prototype['party'] = undefined;
  /**
   * @member {Array.<module:model/CaseAliasInnerPartyAlias>} party_alias
   */
  exports.prototype['party_alias'] = undefined;



  return exports;
}));


