/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CaseCreditorMailingMetaPdf'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CaseCreditorMailingMetaPdf'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.CaseCreditorMailingMeta = factory(root.CourtApi.ApiClient, root.CourtApi.CaseCreditorMailingMetaPdf);
  }
}(this, function(ApiClient, CaseCreditorMailingMetaPdf) {
  'use strict';




  /**
   * The CaseCreditorMailingMeta model module.
   * @module model/CaseCreditorMailingMeta
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>CaseCreditorMailingMeta</code>.
   * @alias module:model/CaseCreditorMailingMeta
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>CaseCreditorMailingMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CaseCreditorMailingMeta} obj Optional instance to populate.
   * @return {module:model/CaseCreditorMailingMeta} The populated <code>CaseCreditorMailingMeta</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('pdf')) {
        obj['pdf'] = CaseCreditorMailingMetaPdf.constructFromObject(data['pdf']);
      }
      if (data.hasOwnProperty('csv')) {
        obj['csv'] = CaseCreditorMailingMetaPdf.constructFromObject(data['csv']);
      }
      if (data.hasOwnProperty('case_uuid')) {
        obj['case_uuid'] = ApiClient.convertToType(data['case_uuid'], 'String');
      }
      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/CaseCreditorMailingMetaPdf} pdf
   */
  exports.prototype['pdf'] = undefined;
  /**
   * @member {module:model/CaseCreditorMailingMetaPdf} csv
   */
  exports.prototype['csv'] = undefined;
  /**
   * @member {String} case_uuid
   */
  exports.prototype['case_uuid'] = undefined;
  /**
   * @member {String} timestamp
   */
  exports.prototype['timestamp'] = undefined;



  return exports;
}));


