/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2001QueriesMenuMeta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse2001QueriesMenuMeta'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse20013QueriesCreditorMailing = factory(root.CourtApi.ApiClient, root.CourtApi.InlineResponse2001QueriesMenuMeta);
  }
}(this, function(ApiClient, InlineResponse2001QueriesMenuMeta) {
  'use strict';




  /**
   * The InlineResponse20013QueriesCreditorMailing model module.
   * @module model/InlineResponse20013QueriesCreditorMailing
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse20013QueriesCreditorMailing</code>.
   * @alias module:model/InlineResponse20013QueriesCreditorMailing
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>InlineResponse20013QueriesCreditorMailing</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20013QueriesCreditorMailing} obj Optional instance to populate.
   * @return {module:model/InlineResponse20013QueriesCreditorMailing} The populated <code>InlineResponse20013QueriesCreditorMailing</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('meta')) {
        obj['meta'] = InlineResponse2001QueriesMenuMeta.constructFromObject(data['meta']);
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], 'String');
      }
      if (data.hasOwnProperty('csv')) {
        obj['csv'] = ApiClient.convertToType(data['csv'], 'String');
      }
      if (data.hasOwnProperty('pdf')) {
        obj['pdf'] = ApiClient.convertToType(data['pdf'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse2001QueriesMenuMeta} meta
   */
  exports.prototype['meta'] = undefined;
  /**
   * @member {String} text
   */
  exports.prototype['text'] = undefined;
  /**
   * @member {String} csv
   */
  exports.prototype['csv'] = undefined;
  /**
   * @member {String} pdf
   */
  exports.prototype['pdf'] = undefined;



  return exports;
}));


