/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20010QueriesText', 'model/InlineResponse2001QueriesMenuMeta'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20010QueriesText'), require('./InlineResponse2001QueriesMenuMeta'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse20010QueriesTrustees = factory(root.CourtApi.ApiClient, root.CourtApi.InlineResponse20010QueriesText, root.CourtApi.InlineResponse2001QueriesMenuMeta);
  }
}(this, function(ApiClient, InlineResponse20010QueriesText, InlineResponse2001QueriesMenuMeta) {
  'use strict';




  /**
   * The InlineResponse20010QueriesTrustees model module.
   * @module model/InlineResponse20010QueriesTrustees
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse20010QueriesTrustees</code>.
   * @alias module:model/InlineResponse20010QueriesTrustees
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse20010QueriesTrustees</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010QueriesTrustees} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010QueriesTrustees} The populated <code>InlineResponse20010QueriesTrustees</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('meta')) {
        obj['meta'] = InlineResponse2001QueriesMenuMeta.constructFromObject(data['meta']);
      }
      if (data.hasOwnProperty('text')) {
        obj['text'] = ApiClient.convertToType(data['text'], [InlineResponse20010QueriesText]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse2001QueriesMenuMeta} meta
   */
  exports.prototype['meta'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20010QueriesText>} text
   */
  exports.prototype['text'] = undefined;



  return exports;
}));


