/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssociatedCases', 'model/PACERQueryOtherFilings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AssociatedCases'), require('./PACERQueryOtherFilings'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse2003Queries = factory(root.CourtApi.ApiClient, root.CourtApi.AssociatedCases, root.CourtApi.PACERQueryOtherFilings);
  }
}(this, function(ApiClient, AssociatedCases, PACERQueryOtherFilings) {
  'use strict';




  /**
   * The InlineResponse2003Queries model module.
   * @module model/InlineResponse2003Queries
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse2003Queries</code>.
   * @alias module:model/InlineResponse2003Queries
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse2003Queries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003Queries} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003Queries} The populated <code>InlineResponse2003Queries</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('associated_cases')) {
        obj['associated_cases'] = AssociatedCases.constructFromObject(data['associated_cases']);
      }
      if (data.hasOwnProperty('other_filings')) {
        obj['other_filings'] = PACERQueryOtherFilings.constructFromObject(data['other_filings']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/AssociatedCases} associated_cases
   */
  exports.prototype['associated_cases'] = undefined;
  /**
   * @member {module:model/PACERQueryOtherFilings} other_filings
   */
  exports.prototype['other_filings'] = undefined;



  return exports;
}));


