/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NCLCaseMeta', 'model/NCLPartiesMeta', 'model/NCLReceipt'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NCLCaseMeta'), require('./NCLPartiesMeta'), require('./NCLReceipt'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse200Items = factory(root.CourtApi.ApiClient, root.CourtApi.NCLCaseMeta, root.CourtApi.NCLPartiesMeta, root.CourtApi.NCLReceipt);
  }
}(this, function(ApiClient, NCLCaseMeta, NCLPartiesMeta, NCLReceipt) {
  'use strict';




  /**
   * The InlineResponse200Items model module.
   * @module model/InlineResponse200Items
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse200Items</code>.
   * @alias module:model/InlineResponse200Items
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse200Items</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse200Items} obj Optional instance to populate.
   * @return {module:model/InlineResponse200Items} The populated <code>InlineResponse200Items</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('cases')) {
        obj['cases'] = ApiClient.convertToType(data['cases'], [NCLCaseMeta]);
      }
      if (data.hasOwnProperty('parties')) {
        obj['parties'] = ApiClient.convertToType(data['parties'], [NCLPartiesMeta]);
      }
      if (data.hasOwnProperty('receipts')) {
        obj['receipts'] = ApiClient.convertToType(data['receipts'], [NCLReceipt]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/NCLCaseMeta>} cases
   */
  exports.prototype['cases'] = undefined;
  /**
   * @member {Array.<module:model/NCLPartiesMeta>} parties
   */
  exports.prototype['parties'] = undefined;
  /**
   * @member {Array.<module:model/NCLReceipt>} receipts
   */
  exports.prototype['receipts'] = undefined;



  return exports;
}));


