/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CaseSummary', 'model/PACERQueryCaseSummaryAttorneys'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CaseSummary'), require('./PACERQueryCaseSummaryAttorneys'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse20012Queries = factory(root.CourtApi.ApiClient, root.CourtApi.CaseSummary, root.CourtApi.PACERQueryCaseSummaryAttorneys);
  }
}(this, function(ApiClient, CaseSummary, PACERQueryCaseSummaryAttorneys) {
  'use strict';




  /**
   * The InlineResponse20012Queries model module.
   * @module model/InlineResponse20012Queries
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse20012Queries</code>.
   * @alias module:model/InlineResponse20012Queries
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>InlineResponse20012Queries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20012Queries} obj Optional instance to populate.
   * @return {module:model/InlineResponse20012Queries} The populated <code>InlineResponse20012Queries</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('case_summary')) {
        obj['case_summary'] = ApiClient.convertToType(data['case_summary'], [CaseSummary]);
      }
      if (data.hasOwnProperty('case_summary_attorneys')) {
        obj['case_summary_attorneys'] = ApiClient.convertToType(data['case_summary_attorneys'], [PACERQueryCaseSummaryAttorneys]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/CaseSummary>} case_summary
   */
  exports.prototype['case_summary'] = undefined;
  /**
   * @member {Array.<module:model/PACERQueryCaseSummaryAttorneys>} case_summary_attorneys
   */
  exports.prototype['case_summary_attorneys'] = undefined;



  return exports;
}));


