/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20020ContentClaimedAmounts', 'model/InlineResponse20020ContentJsonData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20020ContentClaimedAmounts'), require('./InlineResponse20020ContentJsonData'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse20020Content = factory(root.CourtApi.ApiClient, root.CourtApi.InlineResponse20020ContentClaimedAmounts, root.CourtApi.InlineResponse20020ContentJsonData);
  }
}(this, function(ApiClient, InlineResponse20020ContentClaimedAmounts, InlineResponse20020ContentJsonData) {
  'use strict';




  /**
   * The InlineResponse20020Content model module.
   * @module model/InlineResponse20020Content
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse20020Content</code>.
   * @alias module:model/InlineResponse20020Content
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>InlineResponse20020Content</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20020Content} obj Optional instance to populate.
   * @return {module:model/InlineResponse20020Content} The populated <code>InlineResponse20020Content</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('claimed_amounts')) {
        obj['claimed_amounts'] = InlineResponse20020ContentClaimedAmounts.constructFromObject(data['claimed_amounts']);
      }
      if (data.hasOwnProperty('json_data')) {
        obj['json_data'] = ApiClient.convertToType(data['json_data'], [InlineResponse20020ContentJsonData]);
      }
      if (data.hasOwnProperty('page_size')) {
        obj['page_size'] = ApiClient.convertToType(data['page_size'], 'Number');
      }
      if (data.hasOwnProperty('total_items')) {
        obj['total_items'] = ApiClient.convertToType(data['total_items'], 'Number');
      }
      if (data.hasOwnProperty('total_pages')) {
        obj['total_pages'] = ApiClient.convertToType(data['total_pages'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse20020ContentClaimedAmounts} claimed_amounts
   */
  exports.prototype['claimed_amounts'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20020ContentJsonData>} json_data
   */
  exports.prototype['json_data'] = undefined;
  /**
   * @member {Number} page_size
   */
  exports.prototype['page_size'] = undefined;
  /**
   * @member {Number} total_items
   */
  exports.prototype['total_items'] = undefined;
  /**
   * @member {Number} total_pages
   */
  exports.prototype['total_pages'] = undefined;



  return exports;
}));


