/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20020ContentTextAmounts', 'model/InlineResponse20020ContentTextHistory', 'model/InlineResponse20020ContentTextInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20020ContentTextAmounts'), require('./InlineResponse20020ContentTextHistory'), require('./InlineResponse20020ContentTextInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse20020ContentText = factory(root.CourtApi.ApiClient, root.CourtApi.InlineResponse20020ContentTextAmounts, root.CourtApi.InlineResponse20020ContentTextHistory, root.CourtApi.InlineResponse20020ContentTextInfo);
  }
}(this, function(ApiClient, InlineResponse20020ContentTextAmounts, InlineResponse20020ContentTextHistory, InlineResponse20020ContentTextInfo) {
  'use strict';




  /**
   * The InlineResponse20020ContentText model module.
   * @module model/InlineResponse20020ContentText
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse20020ContentText</code>.
   * @alias module:model/InlineResponse20020ContentText
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>InlineResponse20020ContentText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20020ContentText} obj Optional instance to populate.
   * @return {module:model/InlineResponse20020ContentText} The populated <code>InlineResponse20020ContentText</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('amounts')) {
        obj['amounts'] = InlineResponse20020ContentTextAmounts.constructFromObject(data['amounts']);
      }
      if (data.hasOwnProperty('creditor')) {
        obj['creditor'] = ApiClient.convertToType(data['creditor'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('history')) {
        obj['history'] = ApiClient.convertToType(data['history'], [InlineResponse20020ContentTextHistory]);
      }
      if (data.hasOwnProperty('info')) {
        obj['info'] = InlineResponse20020ContentTextInfo.constructFromObject(data['info']);
      }
      if (data.hasOwnProperty('remarks')) {
        obj['remarks'] = ApiClient.convertToType(data['remarks'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse20020ContentTextAmounts} amounts
   */
  exports.prototype['amounts'] = undefined;
  /**
   * @member {String} creditor
   */
  exports.prototype['creditor'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Array.<module:model/InlineResponse20020ContentTextHistory>} history
   */
  exports.prototype['history'] = undefined;
  /**
   * @member {module:model/InlineResponse20020ContentTextInfo} info
   */
  exports.prototype['info'] = undefined;
  /**
   * @member {String} remarks
   */
  exports.prototype['remarks'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


