/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse20014QueriesHistory'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse20014QueriesHistory'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.InlineResponse20014Queries = factory(root.CourtApi.ApiClient, root.CourtApi.InlineResponse20014QueriesHistory);
  }
}(this, function(ApiClient, InlineResponse20014QueriesHistory) {
  'use strict';




  /**
   * The InlineResponse20014Queries model module.
   * @module model/InlineResponse20014Queries
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>InlineResponse20014Queries</code>.
   * @alias module:model/InlineResponse20014Queries
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>InlineResponse20014Queries</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20014Queries} obj Optional instance to populate.
   * @return {module:model/InlineResponse20014Queries} The populated <code>InlineResponse20014Queries</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('history')) {
        obj['history'] = InlineResponse20014QueriesHistory.constructFromObject(data['history']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/InlineResponse20014QueriesHistory} history
   */
  exports.prototype['history'] = undefined;



  return exports;
}));


