/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PACERQueryCaseSummaryAttorneysAssociated', 'model/PACERQueryCaseSummaryAttorneysAttorney'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PACERQueryCaseSummaryAttorneysAssociated'), require('./PACERQueryCaseSummaryAttorneysAttorney'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.PACERQueryCaseSummaryAttorneysText = factory(root.CourtApi.ApiClient, root.CourtApi.PACERQueryCaseSummaryAttorneysAssociated, root.CourtApi.PACERQueryCaseSummaryAttorneysAttorney);
  }
}(this, function(ApiClient, PACERQueryCaseSummaryAttorneysAssociated, PACERQueryCaseSummaryAttorneysAttorney) {
  'use strict';




  /**
   * The PACERQueryCaseSummaryAttorneysText model module.
   * @module model/PACERQueryCaseSummaryAttorneysText
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>PACERQueryCaseSummaryAttorneysText</code>.
   * @alias module:model/PACERQueryCaseSummaryAttorneysText
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PACERQueryCaseSummaryAttorneysText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PACERQueryCaseSummaryAttorneysText} obj Optional instance to populate.
   * @return {module:model/PACERQueryCaseSummaryAttorneysText} The populated <code>PACERQueryCaseSummaryAttorneysText</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('associated')) {
        obj['associated'] = ApiClient.convertToType(data['associated'], [PACERQueryCaseSummaryAttorneysAssociated]);
      }
      if (data.hasOwnProperty('attorney')) {
        obj['attorney'] = PACERQueryCaseSummaryAttorneysAttorney.constructFromObject(data['attorney']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/PACERQueryCaseSummaryAttorneysAssociated>} associated
   */
  exports.prototype['associated'] = undefined;
  /**
   * @member {module:model/PACERQueryCaseSummaryAttorneysAttorney} attorney
   */
  exports.prototype['attorney'] = undefined;



  return exports;
}));


