/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.PACERQueryCaseHeaderText = factory(root.CourtApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PACERQueryCaseHeaderText model module.
   * @module model/PACERQueryCaseHeaderText
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>PACERQueryCaseHeaderText</code>.
   * @alias module:model/PACERQueryCaseHeaderText
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>PACERQueryCaseHeaderText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PACERQueryCaseHeaderText} obj Optional instance to populate.
   * @return {module:model/PACERQueryCaseHeaderText} The populated <code>PACERQueryCaseHeaderText</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('case_code')) {
        obj['case_code'] = ApiClient.convertToType(data['case_code'], 'String');
      }
      if (data.hasOwnProperty('case_title')) {
        obj['case_title'] = ApiClient.convertToType(data['case_title'], 'String');
      }
      if (data.hasOwnProperty('case_type')) {
        obj['case_type'] = ApiClient.convertToType(data['case_type'], 'String');
      }
      if (data.hasOwnProperty('case_uuid')) {
        obj['case_uuid'] = ApiClient.convertToType(data['case_uuid'], 'String');
      }
      if (data.hasOwnProperty('chapter')) {
        obj['chapter'] = ApiClient.convertToType(data['chapter'], 'Number');
      }
      if (data.hasOwnProperty('date_filed')) {
        obj['date_filed'] = ApiClient.convertToType(data['date_filed'], 'String');
      }
      if (data.hasOwnProperty('date_of_last_filing')) {
        obj['date_of_last_filing'] = ApiClient.convertToType(data['date_of_last_filing'], 'String');
      }
      if (data.hasOwnProperty('has_asset')) {
        obj['has_asset'] = ApiClient.convertToType(data['has_asset'], 'String');
      }
      if (data.hasOwnProperty('judge_name')) {
        obj['judge_name'] = ApiClient.convertToType(data['judge_name'], 'String');
      }
      if (data.hasOwnProperty('petition_type')) {
        obj['petition_type'] = ApiClient.convertToType(data['petition_type'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} case_code
   */
  exports.prototype['case_code'] = undefined;
  /**
   * @member {String} case_title
   */
  exports.prototype['case_title'] = undefined;
  /**
   * @member {String} case_type
   */
  exports.prototype['case_type'] = undefined;
  /**
   * @member {String} case_uuid
   */
  exports.prototype['case_uuid'] = undefined;
  /**
   * @member {Number} chapter
   */
  exports.prototype['chapter'] = undefined;
  /**
   * @member {String} date_filed
   */
  exports.prototype['date_filed'] = undefined;
  /**
   * @member {String} date_of_last_filing
   */
  exports.prototype['date_of_last_filing'] = undefined;
  /**
   * @member {String} has_asset
   */
  exports.prototype['has_asset'] = undefined;
  /**
   * @member {String} judge_name
   */
  exports.prototype['judge_name'] = undefined;
  /**
   * @member {String} petition_type
   */
  exports.prototype['petition_type'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;



  return exports;
}));


