/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CaseAttorneysInnerAssociated', 'model/PACERQueryCaseAttorneysItemsInnerText'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CaseAttorneysInnerAssociated'), require('./PACERQueryCaseAttorneysItemsInnerText'));
  } else {
    // Browser globals (root is window)
    if (!root.CourtApi) {
      root.CourtApi = {};
    }
    root.CourtApi.PACERQueryCaseAttorneysInnerText = factory(root.CourtApi.ApiClient, root.CourtApi.CaseAttorneysInnerAssociated, root.CourtApi.PACERQueryCaseAttorneysItemsInnerText);
  }
}(this, function(ApiClient, CaseAttorneysInnerAssociated, PACERQueryCaseAttorneysItemsInnerText) {
  'use strict';




  /**
   * The PACERQueryCaseAttorneysInnerText model module.
   * @module model/PACERQueryCaseAttorneysInnerText
   * @version 0.9.2
   */

  /**
   * Constructs a new <code>PACERQueryCaseAttorneysInnerText</code>.
   * @alias module:model/PACERQueryCaseAttorneysInnerText
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>PACERQueryCaseAttorneysInnerText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PACERQueryCaseAttorneysInnerText} obj Optional instance to populate.
   * @return {module:model/PACERQueryCaseAttorneysInnerText} The populated <code>PACERQueryCaseAttorneysInnerText</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('attorney')) {
        obj['attorney'] = PACERQueryCaseAttorneysItemsInnerText.constructFromObject(data['attorney']);
      }
      if (data.hasOwnProperty('associated')) {
        obj['associated'] = ApiClient.convertToType(data['associated'], [CaseAttorneysInnerAssociated]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PACERQueryCaseAttorneysItemsInnerText} attorney
   */
  exports.prototype['attorney'] = undefined;
  /**
   * @member {Array.<module:model/CaseAttorneysInnerAssociated>} associated
   */
  exports.prototype['associated'] = undefined;



  return exports;
}));


