/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.DocketSearchDocketEntryMeta();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DocketSearchDocketEntryMeta', function() {
    it('should create an instance of DocketSearchDocketEntryMeta', function() {
      // uncomment below and update the code to test DocketSearchDocketEntryMeta
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be.a(CourtApi.DocketSearchDocketEntryMeta);
    });

    it('should have the property annotations (base name: "annotations")', function() {
      // uncomment below and update the code to test the property annotations
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property caseUuid (base name: "case_uuid")', function() {
      // uncomment below and update the code to test the property caseUuid
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property dateFiled (base name: "date_filed")', function() {
      // uncomment below and update the code to test the property dateFiled
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property docketNo (base name: "docket_no")', function() {
      // uncomment below and update the code to test the property docketNo
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property docketSeq (base name: "docket_seq")', function() {
      // uncomment below and update the code to test the property docketSeq
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property docketText (base name: "docket_text")', function() {
      // uncomment below and update the code to test the property docketText
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new CourtApi.DocketSearchDocketEntryMeta();
      //expect(instance).to.be();
    });

  });

}));
