/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20015ItemsRelatedTransactions', function() {
    it('should create an instance of InlineResponse20015ItemsRelatedTransactions', function() {
      // uncomment below and update the code to test InlineResponse20015ItemsRelatedTransactions
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be.a(CourtApi.InlineResponse20015ItemsRelatedTransactions);
    });

    it('should have the property caseUuid (base name: "case_uuid")', function() {
      // uncomment below and update the code to test the property caseUuid
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property dateEventFiled (base name: "date_event_filed")', function() {
      // uncomment below and update the code to test the property dateEventFiled
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property dateEventTerminated (base name: "date_event_terminated")', function() {
      // uncomment below and update the code to test the property dateEventTerminated
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property dateFiled (base name: "date_filed")', function() {
      // uncomment below and update the code to test the property dateFiled
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property docketNo (base name: "docket_no")', function() {
      // uncomment below and update the code to test the property docketNo
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property docketSeq (base name: "docket_seq")', function() {
      // uncomment below and update the code to test the property docketSeq
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property docketUri (base name: "docket_uri")', function() {
      // uncomment below and update the code to test the property docketUri
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property eventName (base name: "event_name")', function() {
      // uncomment below and update the code to test the property eventName
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property eventUri (base name: "event_uri")', function() {
      // uncomment below and update the code to test the property eventUri
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property filename (base name: "filename")', function() {
      // uncomment below and update the code to test the property filename
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property orderDocketNo (base name: "order_docket_no")', function() {
      // uncomment below and update the code to test the property orderDocketNo
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property orderDocketSeq (base name: "order_docket_seq")', function() {
      // uncomment below and update the code to test the property orderDocketSeq
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property related (base name: "related")', function() {
      // uncomment below and update the code to test the property related
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instane = new CourtApi.InlineResponse20015ItemsRelatedTransactions();
      //expect(instance).to.be();
    });

  });

}));
