/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.InlineResponse20020Content();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20020Content', function() {
    it('should create an instance of InlineResponse20020Content', function() {
      // uncomment below and update the code to test InlineResponse20020Content
      //var instane = new CourtApi.InlineResponse20020Content();
      //expect(instance).to.be.a(CourtApi.InlineResponse20020Content);
    });

    it('should have the property claimedAmounts (base name: "claimed_amounts")', function() {
      // uncomment below and update the code to test the property claimedAmounts
      //var instane = new CourtApi.InlineResponse20020Content();
      //expect(instance).to.be();
    });

    it('should have the property jsonData (base name: "json_data")', function() {
      // uncomment below and update the code to test the property jsonData
      //var instane = new CourtApi.InlineResponse20020Content();
      //expect(instance).to.be();
    });

    it('should have the property pageSize (base name: "page_size")', function() {
      // uncomment below and update the code to test the property pageSize
      //var instane = new CourtApi.InlineResponse20020Content();
      //expect(instance).to.be();
    });

    it('should have the property totalItems (base name: "total_items")', function() {
      // uncomment below and update the code to test the property totalItems
      //var instane = new CourtApi.InlineResponse20020Content();
      //expect(instance).to.be();
    });

    it('should have the property totalPages (base name: "total_pages")', function() {
      // uncomment below and update the code to test the property totalPages
      //var instane = new CourtApi.InlineResponse20020Content();
      //expect(instance).to.be();
    });

  });

}));
