/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.InlineResponse20019Forms();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20019Forms', function() {
    it('should create an instance of InlineResponse20019Forms', function() {
      // uncomment below and update the code to test InlineResponse20019Forms
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be.a(CourtApi.InlineResponse20019Forms);
    });

    it('should have the property caseCode (base name: "case_code")', function() {
      // uncomment below and update the code to test the property caseCode
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property creditorName (base name: "creditor_name")', function() {
      // uncomment below and update the code to test the property creditorName
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property creditorNo (base name: "creditor_no")', function() {
      // uncomment below and update the code to test the property creditorNo
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property creditorType (base name: "creditor_type")', function() {
      // uncomment below and update the code to test the property creditorType
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property dateFrom (base name: "date_from")', function() {
      // uncomment below and update the code to test the property dateFrom
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property dateTo (base name: "date_to")', function() {
      // uncomment below and update the code to test the property dateTo
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property docFrom (base name: "doc_from")', function() {
      // uncomment below and update the code to test the property docFrom
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

    it('should have the property docTo (base name: "doc_to")', function() {
      // uncomment below and update the code to test the property docTo
      //var instane = new CourtApi.InlineResponse20019Forms();
      //expect(instance).to.be();
    });

  });

}));
