/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.CaseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CaseApi', function() {
    describe('getAssociatedCases', function() {
      it('should call getAssociatedCases successfully', function(done) {
        //uncomment below and update the code to test getAssociatedCases
        //instance.getAssociatedCases(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAttorneys', function() {
      it('should call getAttorneys successfully', function(done) {
        //uncomment below and update the code to test getAttorneys
        //instance.getAttorneys(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCaseMenu', function() {
      it('should call getCaseMenu successfully', function(done) {
        //uncomment below and update the code to test getCaseMenu
        //instance.getCaseMenu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaim', function() {
      it('should call getClaim successfully', function(done) {
        //uncomment below and update the code to test getClaim
        //instance.getClaim(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaimDocument', function() {
      it('should call getClaimDocument successfully', function(done) {
        //uncomment below and update the code to test getClaimDocument
        //instance.getClaimDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaimParts', function() {
      it('should call getClaimParts successfully', function(done) {
        //uncomment below and update the code to test getClaimParts
        //instance.getClaimParts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaims', function() {
      it('should call getClaims successfully', function(done) {
        //uncomment below and update the code to test getClaims
        //instance.getClaims(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaimsHeader', function() {
      it('should call getClaimsHeader successfully', function(done) {
        //uncomment below and update the code to test getClaimsHeader
        //instance.getClaimsHeader(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCreditorMailingMatrix', function() {
      it('should call getCreditorMailingMatrix successfully', function(done) {
        //uncomment below and update the code to test getCreditorMailingMatrix
        //instance.getCreditorMailingMatrix(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCreditors', function() {
      it('should call getCreditors successfully', function(done) {
        //uncomment below and update the code to test getCreditors
        //instance.getCreditors(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketDocument', function() {
      it('should call getDocketDocument successfully', function(done) {
        //uncomment below and update the code to test getDocketDocument
        //instance.getDocketDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketDocuments', function() {
      it('should call getDocketDocuments successfully', function(done) {
        //uncomment below and update the code to test getDocketDocuments
        //instance.getDocketDocuments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketEntry', function() {
      it('should call getDocketEntry successfully', function(done) {
        //uncomment below and update the code to test getDocketEntry
        //instance.getDocketEntry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketHeader', function() {
      it('should call getDocketHeader successfully', function(done) {
        //uncomment below and update the code to test getDocketHeader
        //instance.getDocketHeader(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDockets', function() {
      it('should call getDockets successfully', function(done) {
        //uncomment below and update the code to test getDockets
        //instance.getDockets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFilers', function() {
      it('should call getFilers successfully', function(done) {
        //uncomment below and update the code to test getFilers
        //instance.getFilers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHeaders', function() {
      it('should call getHeaders successfully', function(done) {
        //uncomment below and update the code to test getHeaders
        //instance.getHeaders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMenu', function() {
      it('should call getMenu successfully', function(done) {
        //uncomment below and update the code to test getMenu
        //instance.getMenu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNotice', function() {
      it('should call getNotice successfully', function(done) {
        //uncomment below and update the code to test getNotice
        //instance.getNotice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParties', function() {
      it('should call getParties successfully', function(done) {
        //uncomment below and update the code to test getParties
        //instance.getParties(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPartyAliases', function() {
      it('should call getPartyAliases successfully', function(done) {
        //uncomment below and update the code to test getPartyAliases
        //instance.getPartyAliases(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPendingStatus', function() {
      it('should call getPendingStatus successfully', function(done) {
        //uncomment below and update the code to test getPendingStatus
        //instance.getPendingStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSchedule', function() {
      it('should call getSchedule successfully', function(done) {
        //uncomment below and update the code to test getSchedule
        //instance.getSchedule(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSummary', function() {
      it('should call getSummary successfully', function(done) {
        //uncomment below and update the code to test getSummary
        //instance.getSummary(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTrustees', function() {
      it('should call getTrustees successfully', function(done) {
        //uncomment below and update the code to test getTrustees
        //instance.getTrustees(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
