/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.CaseApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CaseApi', function() {
    describe('casesPacerCourtCodeCaseNumberAliasGet', function() {
      it('should call casesPacerCourtCodeCaseNumberAliasGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberAliasGet
        //instance.casesPacerCourtCodeCaseNumberAliasGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberAssociatedCasesGet', function() {
      it('should call casesPacerCourtCodeCaseNumberAssociatedCasesGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberAssociatedCasesGet
        //instance.casesPacerCourtCodeCaseNumberAssociatedCasesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberAttorneysGet', function() {
      it('should call casesPacerCourtCodeCaseNumberAttorneysGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberAttorneysGet
        //instance.casesPacerCourtCodeCaseNumberAttorneysGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCaseSummaryGet', function() {
      it('should call casesPacerCourtCodeCaseNumberCaseSummaryGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCaseSummaryGet
        //instance.casesPacerCourtCodeCaseNumberCaseSummaryGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCreditorMailingGet', function() {
      it('should call casesPacerCourtCodeCaseNumberCreditorMailingGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCreditorMailingGet
        //instance.casesPacerCourtCodeCaseNumberCreditorMailingGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCreditorsGet', function() {
      it('should call casesPacerCourtCodeCaseNumberCreditorsGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCreditorsGet
        //instance.casesPacerCourtCodeCaseNumberCreditorsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberFilersGet', function() {
      it('should call casesPacerCourtCodeCaseNumberFilersGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberFilersGet
        //instance.casesPacerCourtCodeCaseNumberFilersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberMenuGet', function() {
      it('should call casesPacerCourtCodeCaseNumberMenuGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberMenuGet
        //instance.casesPacerCourtCodeCaseNumberMenuGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberNoticeGet', function() {
      it('should call casesPacerCourtCodeCaseNumberNoticeGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberNoticeGet
        //instance.casesPacerCourtCodeCaseNumberNoticeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberPartiesGet', function() {
      it('should call casesPacerCourtCodeCaseNumberPartiesGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberPartiesGet
        //instance.casesPacerCourtCodeCaseNumberPartiesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberScheduleGet', function() {
      it('should call casesPacerCourtCodeCaseNumberScheduleGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberScheduleGet
        //instance.casesPacerCourtCodeCaseNumberScheduleGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberStatusPendingGet', function() {
      it('should call casesPacerCourtCodeCaseNumberStatusPendingGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberStatusPendingGet
        //instance.casesPacerCourtCodeCaseNumberStatusPendingGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberTrusteesGet', function() {
      it('should call casesPacerCourtCodeCaseNumberTrusteesGet successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberTrusteesGet
        //instance.casesPacerCourtCodeCaseNumberTrusteesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCaseMenu', function() {
      it('should call getCaseMenu successfully', function(done) {
        //uncomment below and update the code to test getCaseMenu
        //instance.getCaseMenu(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaim', function() {
      it('should call getClaim successfully', function(done) {
        //uncomment below and update the code to test getClaim
        //instance.getClaim(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaimDocument', function() {
      it('should call getClaimDocument successfully', function(done) {
        //uncomment below and update the code to test getClaimDocument
        //instance.getClaimDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaimParts', function() {
      it('should call getClaimParts successfully', function(done) {
        //uncomment below and update the code to test getClaimParts
        //instance.getClaimParts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaims', function() {
      it('should call getClaims successfully', function(done) {
        //uncomment below and update the code to test getClaims
        //instance.getClaims(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClaimsHeader', function() {
      it('should call getClaimsHeader successfully', function(done) {
        //uncomment below and update the code to test getClaimsHeader
        //instance.getClaimsHeader(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketDocument', function() {
      it('should call getDocketDocument successfully', function(done) {
        //uncomment below and update the code to test getDocketDocument
        //instance.getDocketDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketDocuments', function() {
      it('should call getDocketDocuments successfully', function(done) {
        //uncomment below and update the code to test getDocketDocuments
        //instance.getDocketDocuments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketEntry', function() {
      it('should call getDocketEntry successfully', function(done) {
        //uncomment below and update the code to test getDocketEntry
        //instance.getDocketEntry(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDocketHeader', function() {
      it('should call getDocketHeader successfully', function(done) {
        //uncomment below and update the code to test getDocketHeader
        //instance.getDocketHeader(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDockets', function() {
      it('should call getDockets successfully', function(done) {
        //uncomment below and update the code to test getDockets
        //instance.getDockets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getHeaders', function() {
      it('should call getHeaders successfully', function(done) {
        //uncomment below and update the code to test getHeaders
        //instance.getHeaders(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
