/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.NclApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NclApi', function() {
    describe('pacerNclAppellatePost', function() {
      it('should call pacerNclAppellatePost successfully', function(done) {
        //uncomment below and update the code to test pacerNclAppellatePost
        //instance.pacerNclAppellatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclAppellateSearchIdGet', function() {
      it('should call pacerNclAppellateSearchIdGet successfully', function(done) {
        //uncomment below and update the code to test pacerNclAppellateSearchIdGet
        //instance.pacerNclAppellateSearchIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclBankruptcyPost', function() {
      it('should call pacerNclBankruptcyPost successfully', function(done) {
        //uncomment below and update the code to test pacerNclBankruptcyPost
        //instance.pacerNclBankruptcyPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclBankruptcySearchIdGet', function() {
      it('should call pacerNclBankruptcySearchIdGet successfully', function(done) {
        //uncomment below and update the code to test pacerNclBankruptcySearchIdGet
        //instance.pacerNclBankruptcySearchIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclCivilPost', function() {
      it('should call pacerNclCivilPost successfully', function(done) {
        //uncomment below and update the code to test pacerNclCivilPost
        //instance.pacerNclCivilPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclCivilSearchIdGet', function() {
      it('should call pacerNclCivilSearchIdGet successfully', function(done) {
        //uncomment below and update the code to test pacerNclCivilSearchIdGet
        //instance.pacerNclCivilSearchIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclCriminalPost', function() {
      it('should call pacerNclCriminalPost successfully', function(done) {
        //uncomment below and update the code to test pacerNclCriminalPost
        //instance.pacerNclCriminalPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclCriminalSearchIdGet', function() {
      it('should call pacerNclCriminalSearchIdGet successfully', function(done) {
        //uncomment below and update the code to test pacerNclCriminalSearchIdGet
        //instance.pacerNclCriminalSearchIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclMdlPost', function() {
      it('should call pacerNclMdlPost successfully', function(done) {
        //uncomment below and update the code to test pacerNclMdlPost
        //instance.pacerNclMdlPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('pacerNclMdlSearchIdGet', function() {
      it('should call pacerNclMdlSearchIdGet successfully', function(done) {
        //uncomment below and update the code to test pacerNclMdlSearchIdGet
        //instance.pacerNclMdlSearchIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
