/**
 * CourtAPI
 * Automate PACER Access
 *
 * OpenAPI spec version: 0.9.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CourtApi);
  }
}(this, function(expect, CourtApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CourtApi.QueryApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QueryApi', function() {
    describe('buyClaimDocument', function() {
      it('should call buyClaimDocument successfully', function(done) {
        //uncomment below and update the code to test buyClaimDocument
        //instance.buyClaimDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buyDocketDocument', function() {
      it('should call buyDocketDocument successfully', function(done) {
        //uncomment below and update the code to test buyDocketDocument
        //instance.buyDocketDocument(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberAliasPost', function() {
      it('should call casesPacerCourtCodeCaseNumberAliasPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberAliasPost
        //instance.casesPacerCourtCodeCaseNumberAliasPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberAssociatedCasesPost', function() {
      it('should call casesPacerCourtCodeCaseNumberAssociatedCasesPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberAssociatedCasesPost
        //instance.casesPacerCourtCodeCaseNumberAssociatedCasesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberAttorneysPost', function() {
      it('should call casesPacerCourtCodeCaseNumberAttorneysPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberAttorneysPost
        //instance.casesPacerCourtCodeCaseNumberAttorneysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCaseFileLocationPost', function() {
      it('should call casesPacerCourtCodeCaseNumberCaseFileLocationPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCaseFileLocationPost
        //instance.casesPacerCourtCodeCaseNumberCaseFileLocationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCaseSummaryPost', function() {
      it('should call casesPacerCourtCodeCaseNumberCaseSummaryPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCaseSummaryPost
        //instance.casesPacerCourtCodeCaseNumberCaseSummaryPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCreditorMailingPost', function() {
      it('should call casesPacerCourtCodeCaseNumberCreditorMailingPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCreditorMailingPost
        //instance.casesPacerCourtCodeCaseNumberCreditorMailingPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberCreditorsPost', function() {
      it('should call casesPacerCourtCodeCaseNumberCreditorsPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberCreditorsPost
        //instance.casesPacerCourtCodeCaseNumberCreditorsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberFilersPost', function() {
      it('should call casesPacerCourtCodeCaseNumberFilersPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberFilersPost
        //instance.casesPacerCourtCodeCaseNumberFilersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberHistoryPost', function() {
      it('should call casesPacerCourtCodeCaseNumberHistoryPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberHistoryPost
        //instance.casesPacerCourtCodeCaseNumberHistoryPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberMenuPost', function() {
      it('should call casesPacerCourtCodeCaseNumberMenuPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberMenuPost
        //instance.casesPacerCourtCodeCaseNumberMenuPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberNoticePost', function() {
      it('should call casesPacerCourtCodeCaseNumberNoticePost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberNoticePost
        //instance.casesPacerCourtCodeCaseNumberNoticePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberPartiesPost', function() {
      it('should call casesPacerCourtCodeCaseNumberPartiesPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberPartiesPost
        //instance.casesPacerCourtCodeCaseNumberPartiesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberRelatedTransactionsPost', function() {
      it('should call casesPacerCourtCodeCaseNumberRelatedTransactionsPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberRelatedTransactionsPost
        //instance.casesPacerCourtCodeCaseNumberRelatedTransactionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberSchedulePost', function() {
      it('should call casesPacerCourtCodeCaseNumberSchedulePost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberSchedulePost
        //instance.casesPacerCourtCodeCaseNumberSchedulePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberStatusPendingPost', function() {
      it('should call casesPacerCourtCodeCaseNumberStatusPendingPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberStatusPendingPost
        //instance.casesPacerCourtCodeCaseNumberStatusPendingPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('casesPacerCourtCodeCaseNumberTrusteesPost', function() {
      it('should call casesPacerCourtCodeCaseNumberTrusteesPost successfully', function(done) {
        //uncomment below and update the code to test casesPacerCourtCodeCaseNumberTrusteesPost
        //instance.casesPacerCourtCodeCaseNumberTrusteesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateClaimParts', function() {
      it('should call updateClaimParts successfully', function(done) {
        //uncomment below and update the code to test updateClaimParts
        //instance.updateClaimParts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateClaims', function() {
      it('should call updateClaims successfully', function(done) {
        //uncomment below and update the code to test updateClaims
        //instance.updateClaims(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDocketDocuments', function() {
      it('should call updateDocketDocuments successfully', function(done) {
        //uncomment below and update the code to test updateDocketDocuments
        //instance.updateDocketDocuments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDockets', function() {
      it('should call updateDockets successfully', function(done) {
        //uncomment below and update the code to test updateDockets
        //instance.updateDockets(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
